root = "."
tmp_dir = "tmp"

[build]
    cmd = "go run ./cmd/server/main.go"
    bin = "tmp/main.exe"
    include_ext = ["go", "yaml", "yml", "env"]
    exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
    exclude_file = []
    delay = 1000
    send_interrupt = true
    log = "build.log"

[log]
    time = true

[color]
    main = "magenta"
    watcher = "cyan"
    build = "yellow"
    runner = "green"
