root = "."
tmp_dir = "./log/tmp"

[build]
    cmd = "go build -o ./cmd/server/tmp/main ./cmd/server/main.go"
    bin = "./cmd/server/tmp/main"
    include_ext = ["go", "yaml", "yml", "env"]
    exclude_dir = ["assets", "tmp", "vendor", "frontend/node_modules"]
    exclude_file = []
    delay = 200
    send_interrupt = true
    stop_on_error = true
    log = "build.log"

[log]
    time = true

[color]
    main = "magenta"
    watcher = "cyan"
    build = "yellow"
    runner = "green"
